import 'antd/dist/antd.css';
import type {AppProps} from 'next/app'
import {appWithTranslation} from "next-i18next";
import Layouts from "../components/layouts/layouts";
import React from "react";
import Head from "next/head";
import {SWRConfig} from "swr";

function MyApp({Component, pageProps}: AppProps) {

	return (
		<>
			<SWRConfig value={{
				onError: (error, key) => {
					if (error){
						console.log({...error})
						console.log(error, 'config error cached')
					}
				}
			}}>
				<Head>
					<title>Jeams</title>
					<meta name="description" content="Generated by create next app"/>
					<link rel="icon" href="/favicon.ico"/>
				</Head>
				<Layouts {...pageProps}><Component {...pageProps} /></Layouts>
			</SWRConfig>
		</>
	)
}

export default appWithTranslation(MyApp);

