import Head from "next/head";
import React, {FC} from "react";

interface Props {
	addTitle?: string
}

const Heads: FC<Props> = ({addTitle}) => {
	return (
		<Head>
			<title>{addTitle ? `${addTitle} | Jeams` : 'Jeams'}</title>
			<meta name="description" content="Generated by create next app"/>
			<link rel="icon" href="../../public/favicon.ico"/>
		</Head>
	)
}


export default Heads